## Atividade 3
### Allan Pereira Fenelon

In [105]:
import numpy as np
from scipy.linalg import qr, lstsq, svd

## 3) (Exercício Computacional) Considere o problema por mínimos quadrados $\min\left\| Ax -b\right\|_2$, onde

In [106]:
A = np.array([[1, 7, 8, 16], 
             [2 , 6, 8, 16],
             [3, 4, 7, 14],
             [-1, 5, 4, 8],
             [0, 1, 1, 2]])

### a) encontre $x_{básico}$ e $x^+$ usando QR com e sem pivotamento, e também SVD.

OBS:

$x_{básico}$ é uma solução básica do sistema $Ax=b$;

$x^+$ é a solução de mínimos quadrados que minimiza $\min\left\| Ax -b\right\|_2$.

Como o vetor b não foi fornecido no enunciado da questão vamoss colcoar um vetor b tal que:


In [107]:
b = np.array([16,16,14,8,2])
b = b.reshape(-1,1)

Agora podemos encontar o nosso $x_{básico}$ e $x^+$

- Encontraremos nesta etapata $x_{básico}$.

__SEM PIVOTAEMENTO__

Como $x_{básico}$ é uma solução básica do sistema $Ax=b$, então se $A=QR$ então $QRx=b$ e logo $Rx_{básico}=Q^Tb$.

Logo, $x_{básico} = R^+Q^Tb$, onde $R^+$ é a pseudo inversa de R.

In [108]:
Q, R = qr(A, mode='full')

x_basico = np.linalg.pinv(R) @ (Q.T @ b)

print("Solução básica x_basico:")
print(x_basico)

Solução básica x_basico:
[[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]


In [109]:
Ax_basico = np.dot(A, x_basico)
Ax_basico

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [110]:
print("Verificando a solução x_básico:")
print(np.allclose(Ax_basico, b))

Verificando a solução x_básico:
True


__COM PIVOTAMENTO__


Como $x_{básico}$ é uma solução básica do sistema $APx=b$, então se $AP=QR$, logo $A=QRP^{-1}=QRP^T$ então $QRP^Tx=b$ e logo $x_{básico}=PR^+Q^Tb$.


In [111]:
Q, R, P = qr(A, pivoting=True, mode='full')

# Construindo a matriz de permutação P_matrix
P_matrix = np.eye(A.shape[1])[P]  

x_basico_piv = P_matrix.T @ np.linalg.pinv(R) @ Q.T @ b

print("Solução x_basico (QR com pivotamento):")
print(x_basico_piv)

Solução x_basico (QR com pivotamento):
[[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]


In [112]:
Ax_basico_piv = np.dot(A, x_basico_piv)
Ax_basico_piv

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [113]:
print("Verificando a solução x_basico:")
print(np.allclose(Ax_basico_piv, b)) 

Verificando a solução x_basico:
True


__COM SVD__

Como $x_{básico}$ é uma solução básica do sistema $Ax=b$, então se $A=U \Sigma V^T$ então $U \Sigma V^Tx=b$ e logo $ \Sigma V^Tx_{básico}=U^Tb$.

Logo, $x_{básico} = V\Sigma^+U^Tb$.

In [114]:
U, S, Vt = svd(A, full_matrices=False)

# Criando S_inv como uma matriz diagonal de tamanho p x p
S_inv = np.zeros_like(Vt.T)
for i in range(len(S)):
    if S[i] > 1e-10:  
        S_inv[i, i] = 1 / S[i]

x_basico_svd = Vt.T @ S_inv @ U.T

print("Solução básica x_basico_svd:")
print(x_basico_svd)

Solução básica x_basico_svd:
[[-0.05362823  0.02944005  0.12959538 -0.15141652 -0.01708706]
 [ 0.05540351 -0.01938013 -0.11043716  0.13987721  0.01627339]
 [ 0.00177528  0.01005992  0.01915822 -0.01153932 -0.00081367]
 [ 0.00355056  0.02011983  0.03831644 -0.02307863 -0.00162734]]


In [115]:
Ax_basico_SVD = np.dot(A, x_basico_piv)
Ax_basico_SVD

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [116]:
print("Verificando a solução x_basico_svd:")
print(np.allclose(Ax_basico_SVD, b)) 

Verificando a solução x_basico_svd:
True


- Encontraremos nesta etapata $x^+$.

$x^+$ é a solução de mínimos quadrados que minimiza $J(x) = \left\| Ax -b\right\|_2^2 = (Ax -b)^T(Ax -b) = x^TA^TAx -2b^TAx+b^Tb$. Logo:

$$
\min\{x^TA^TAx -2b^TAx+b^Tb\} = \frac{dJ(x)}{dx} = 2A^TAx-2A^Tb=0
$$

Portanto:

$$
A^TAx^+= A^Tb
$$


__SEM PIVOTAMENTO__

Temos que:

$$
A^TAx^+= A^Tb
$$

Se $A=QR$ então: 
$$
(QR)^TQRx^+= (QR)^Tb
$$

$$
R^TQ^TQRx^+= R^TQ^Tb
$$

$$
Rx^+= Q^Tb
$$

$$
x^+= R^{-1}Q^Tb
$$

In [117]:
Q, R = qr(A, mode='full')

x_plus = np.linalg.pinv(R) @ Q.T @ b

print("Solução básica x_plus:")
print(x_plus)

Solução básica x_plus:
[[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]


In [118]:
Ax_plus = np.dot(A, x_plus)
Ax_plus

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [119]:
print("Verificando a solução x_plus:")
print(np.allclose(Ax_plus, b)) 

Verificando a solução x_plus:
True


__COM PIVOTAMENTO__

Temos que:

$$
A^TAx^+= A^Tb
$$

Se $AP=QR$ então, $A=QRP^T: 

$$
(QRP^T)^TQRP^Tx^+= (QRP^T)^Tb
$$

$$
PR^TQ^TQRP^Tx^+= PR^TQ^Tb
$$

$$
PR^TRP^Tx^+= PR^TQ^Tb
$$


$$
R^TRP^Tx^+= R^TQ^Tb
$$

$$
RP^Tx^+= Q^Tb
$$

$$
x^+= PR^+Q^Tb
$$




In [120]:
Q, R, P = qr(A, pivoting=True, mode='full')

# Construindo a matriz de permutação P_matrix
P_matrix = np.eye(A.shape[1])[P]  

x_plus_piv = P_matrix.T@np.linalg.pinv(R)@Q.T@b

print("Solução x_plus:")
print(x_plus_piv)

Solução x_plus:
[[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]


In [121]:
Ax_plus_piv = np.dot(A, x_plus_piv)
Ax_plus_piv

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [122]:
print("Verificando a solução x_plus_piv:")
print(np.allclose(Ax_plus_piv, b)) 

Verificando a solução x_plus_piv:
True


__COM SVD__

Temos que:

$$
A^TAx^+= A^Tb
$$

Se $A=U \Sigma V^T$ então: 

$$
(U \Sigma V^T)^TU \Sigma V^Tx^+= (U \Sigma V^T)^Tb
$$

$$
V\Sigma U^TU \Sigma V^Tx^+= V\Sigma U^Tb
$$

$$
V\Sigma^2 V^Tx^+= V\Sigma U^Tb
$$

$$
\Sigma^2 V^Tx^+= \Sigma U^Tb
$$

$$
V^Tx^+= \Sigma^+ U^Tb
$$

$$
x^+= V\Sigma^+ U^Tb
$$





In [123]:
U, S, Vt = svd(A, full_matrices=False)

# Criando S_inv como uma matriz diagonal de tamanho p x p
S_inv = np.zeros_like(Vt.T)
for i in range(len(S)):
    if S[i] > 1e-10:  
        S_inv[i, i] = 1 / S[i]

x_plus_svd = Vt.T @ S_inv @ U.T @b

print("Solução básica x_plus_svd:")
print(x_plus_svd)

Solução básica x_plus_svd:
[[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]


In [124]:
Ax_plus_SVD = np.dot(A, x_plus_svd)
Ax_plus_SVD

array([[16.],
       [16.],
       [14.],
       [ 8.],
       [ 2.]])

In [125]:
print("Verificando a solução x_plus_SVD:")
print(np.allclose(Ax_plus_SVD, b)) 

Verificando a solução x_plus_SVD:
True


### b) Calcule $\tilde{A} = A + E$, onde E é uma matriz de erros cujos elementos são menores ou igual a $10^{-2}$. Calcule a solução básica e aproximação para $x^+$ desprezando o termo $R_3$ proveniente da matriz R. Compare com a SVD.

In [126]:
R_aprox = R.copy()

R_aprox[-1, :] = 0 

Q_b = Q.T @ b
x_aprox, residuals, rank, s = np.linalg.lstsq(R_aprox, Q_b, rcond=None)

In [127]:
print("Solução aproximada (QR desprezando R_3):", x_aprox)
print("Solução via SVD:", x_plus_svd)
print("Diferença entre as soluções:", np.linalg.norm(x_aprox - x_plus_svd))

Solução aproximada (QR desprezando R_3): [[0.72727273]
 [0.18181818]
 [0.18181818]
 [0.36363636]]
Solução via SVD: [[0.18181818]
 [0.18181818]
 [0.36363636]
 [0.72727273]]
Diferença entre as soluções: 0.6803013430498072


## 4)

In [128]:
A = np.array([
    [1, 1000],
    [0,0.001]
])

### a) Calcule a decomposição SVD de A e os valores singulares

In [129]:
U

array([[-0.57937559, -0.2636881 ,  0.73571823, -0.10919463],
       [-0.57197957,  0.13354887, -0.19935076, -0.08672702],
       [-0.49123711,  0.61340147, -0.30123036,  0.09010122],
       [-0.30078181, -0.72769951, -0.56667439, -0.01234502],
       [-0.07334645, -0.08261563,  0.08437041,  0.98604479]])

In [130]:
U

array([[-0.57937559, -0.2636881 ,  0.73571823, -0.10919463],
       [-0.57197957,  0.13354887, -0.19935076, -0.08672702],
       [-0.49123711,  0.61340147, -0.30123036,  0.09010122],
       [-0.30078181, -0.72769951, -0.56667439, -0.01234502],
       [-0.07334645, -0.08261563,  0.08437041,  0.98604479]])

In [131]:
U, S, Vt = svd(A, full_matrices=False)

print('\nMatriz U:\n', U)

print('\nVetor com os valores singulares de A:\n', S)


print('\nMatriz V^T:\n', Vt)




Matriz U:
 [[ 1.00000e+00 -9.99999e-07]
 [ 9.99999e-07  1.00000e+00]]

Vetor com os valores singulares de A:
 [1.0000005e+03 9.9999950e-07]

Matriz V^T:
 [[ 9.999995e-04  9.999995e-01]
 [-9.999995e-01  9.999995e-04]]


### b) Discuta a influência do número de condição da matriz nos valores singulares.

O menor autovalor da matriz A está relacionado ao condicionamento da matriz, se o menor valor singular não-nulo de A for muito pequeno o número de condição da matriz A será grande, o que significa que a matriz A será mal condicionada.

Quando a matriz A é bem condicionada não o menor valor singular comparado ao maior valor singular não é muito pequeno.

In [132]:
print(f"Maior valor singular de A: {S.max()}")
print(f"Menor valor singular de A: {S.min()}")
print(f"Número de condição da matriz A: {np.linalg.cond(A)}")

Maior valor singular de A: 1000.000500000375
Menor valor singular de A: 9.99999499999875e-07
Número de condição da matriz A: 1000001000.0009997


Com as informações que foram impressas podemos afirmar que a matriz A da letra a) é mal-condicionada.

### c) Resolva $Ax=b$ usando SVD e compare com a solução obtida diretamente via $x=A^{-1}b$.

$$
Ax=b
$$

Se $A = U \Sigma V^T$ então:

$$
U \Sigma V^Tx=b
$$

$$
x=V\Sigma^+U^Tb
$$

In [133]:
b = np.array([2,1])

In [134]:
S_inv = np.zeros_like(Vt.T)
for i in range(len(S)):
    if S[i] > 1e-10:  
        S_inv[i, i] = 1 / S[i]

x_svd = Vt.T@S_inv@U.T@b

In [135]:
x_normal = np.linalg.inv(A)@b

In [136]:
print(f'Solução via SVD: {x_svd}\n')
print(f'Solução via equação padrão: {x_normal}\n')

Solução via SVD: [-999998.    1000.]

Solução via equação padrão: [-999998.    1000.]



Não há diferenças numéricas em ambas as soluções. Logo ambas apresentam o mesmo resultado.